### PR TITLE
Add Docker support and fix mono problem

### PR DESCRIPTION
**Pull request by eoftedal**

### CODE REVIEW

**Comment by raybeorn** [comment]
I'll check this out this weekend and get it merged.

**Comment by ProZachJ** [comment]
@raybeorn get to merging boi! 

@eoftedal  Here is a bit cleaner Dockerfile that I've been using (along with your few corrections to the other files)

```
FROM mono
COPY . /usr/local/app/
RUN apt-get update && apt-get upgrade -y && apt-get install -y mono-xsp4 sqlite3
RUN cd /usr/local/app/ && xbuild
CMD cd /usr/local/app/WebGoat && xsp4
```

**Comment by ProZachJ** [comment]
Also the launch command needs a port mapping
```
docker run -t -p 8888:9000 webgoat
```

**Comment by paralax** [comment]
i wrote docker support without first looking at this unmerged PR. mine's using the mono base image and adds a docker-compose YAML config, too, and uses some Docker-isms like WORKDIR instead of the `cd` commands. 

https://github.com/paralax/WebGoat.NET/tree/patch-1

**Comment by eoftedal** [comment]
Closing as this is old

**Pull request closed without merging**
